import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Experimental_CssVarsProvider as CssVarsProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import theme from "@/theme";
import AppLayout from "@/components/layout";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Deez Tunes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <InitColorSchemeScript />
        <CssBaseline enableColorScheme />
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <CssVarsProvider theme={theme}>
            <AppLayout>{children}</AppLayout>
          </CssVarsProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
